### ISSUE TITLE
Chat is not working in android

### ISSUE THREAD

**Issue by francelys04** [aemr3/nativescript-intercom-bridge#9]
Hello, i'm using this library for my project. It works perfect until i open a chat window, when the keyboard ui opens i get the following error:

`System.err: java.lang.NoSuchMethodError: No virtual method onNestedFling(Landroid/support/design/widget/CoordinatorLayout;Landroid/support/design/widget/AppBarLayout;Landroid/view/View;FFZ)Z in class Landroid/support/design/widget/AppBarLayout$Behavior; or its super classes (declaration of 'android.support.design.widget.AppBarLayout$Behavior' appears in /data/app/com.global66.card-1/base.apk)
System.err: 	at io.intercom.android.sdk.profile.ProfilePresenter.flingProfile(ProfilePresenter.java:201)
System.err: 	at io.intercom.android.sdk.profile.ProfilePresenter.flingProfileOpen(ProfilePresenter.java:185)
System.err: 	at io.intercom.android.sdk.profile.ProfilePresenter.profileAutoOpened(ProfilePresenter.java:176)
System.err: 	at io.intercom.android.sdk.conversation.ConversationFragment$6.run(ConversationFragment.java:412)
System.err: 	at android.os.Handler.handleCallback(Handler.java:739)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:145)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6934)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at java.lang.reflect.Method.invoke(Method.java:372)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
ActivityManager: Process com.global66.card (pid 31821)(adj 0) has died(141,225)
ActivityManager: cleanUpApplicationRecord -- 31821
`

"tns-android": "version": "5.1.0"
"nativescript-vue": "^2.0.0"

Worth noting this only happens on android platform, in ios it works properly.

Any ideas why  is this happening?

**Comment by bbroereES** [comment]
I found a solution (maybe a little late) but for reference:
Android use on nativescript-angular requires the following to be added to _dependencies_ in app.gradle:

```
implementation 'io.intercom.android:intercom-sdk-base:5.+'
compile 'com.android.support:multidex:1.0.0'
```
